/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_algos;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import com.google.gson.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    static int getNumberOfMovies(String substr) {
        try {
            URL url = new URL("https://jsonmock.hackerrank.com/api/moviesdata/search/?Title="+substr);
            HttpURLConnection conn = (HttpURLConnection) url.openConnection();
            conn.setRequestMethod("GET");

            // stream reading the response
            BufferedReader in = new BufferedReader(new InputStreamReader(conn.getInputStream()));
            String inputLine;
            StringBuilder content = new StringBuilder();

            while ((inputLine = in.readLine()) != null) {
                content.append(inputLine);
            }
            in.close();
                
            // Close the connection
            conn.disconnect();

            // unmarshal json
            return unmarshalTotal(content.toString());
        } catch(IOException e) {
            System.err.println("Failed to connect the service: " + e.getMessage());
            return 0;
        } catch(JsonParseException e) {
            System.err.println("Failed to unmarshal the response: " + e.getMessage());
            return 0;
        } catch (Exception e) {
            e.printStackTrace();
            return 0;
        }
    }

    static int unmarshalTotal(String response) {
        try {
            // unmarshal json
            JsonParser parser = new JsonParser();
            JsonObject respObj = parser.parse(response).getAsJsonObject();
            return respObj.get("total").getAsInt();
        } catch(JsonParseException e) {
            throw e;
        }
    }

    public static void main(String[] args) {
        System.out.println(new App().getNumberOfMovies(""));
    }
}
